import { EFFECT_IDS, labelFor } from './effects/index.js';

/**
 * Options of the Text module.
 *
 * Attributes: `data-aurora-text="<effect>"` plus
 * `data-aurora-text-<option in kebab-case>`, e.g. `data-aurora-text-split="words"`.
 */
export var schema = {
    primary: 'effect',
    options: {
        effect: {
            type: 'enum',
            default: 'slide-in',
            values: EFFECT_IDS.map(function (id) { return { value: id, label: labelFor(id) }; }),
            label: 'Effect',
            group: 'Effect',
        },
        split: {
            type: 'enum',
            default: 'chars',
            values: ['chars', 'words', 'lines'],
            label: 'Split by',
            description: 'Unit the effect animates. Effects that build their own markup ignore it.',
            group: 'Effect',
        },
        duration: { type: 'number', default: 800, min: 50, max: 10000, unit: 'ms', label: 'Duration', group: 'Timing' },
        delay: { type: 'number', default: 0, min: 0, max: 10000, unit: 'ms', label: 'Delay', group: 'Timing' },
        stagger: { type: 'number', default: 30, min: 0, max: 1000, unit: 'ms', label: 'Stagger', group: 'Timing' },
        trigger: {
            type: 'enum',
            default: 'scroll',
            values: ['scroll', 'load'],
            label: 'Trigger',
            group: 'Trigger',
        },
        threshold: {
            type: 'number',
            default: 0.2,
            min: 0,
            max: 1,
            step: 0.05,
            label: 'Visible ratio',
            description: 'Capped at 5% internally so headings above the fold always start.',
            group: 'Trigger',
            when: { trigger: 'scroll' },
        },
        replay: { type: 'boolean', default: false, label: 'Replay on every scroll', group: 'Trigger', when: { trigger: 'scroll' } },
        target: {
            type: 'selector',
            default: '',
            label: 'Text element',
            description: 'CSS selector, relative to the element, of the node holding the text. Empty uses the element itself.',
            group: 'Advanced',
        },
        direction: {
            type: 'enum',
            default: 'down',
            values: ['up', 'down', 'left', 'right'],
            label: 'Direction',
            description: 'Side the effect enters from. Used by slide-in, flip-in, rotate-in, skew-in and clip-wrap.',
            group: 'Effect',
        },
        style: {
            type: 'enum',
            default: 'smooth',
            values: ['smooth', 'bounce', 'elastic'],
            label: 'Style',
            description: 'Easing character of the slide-in effect.',
            group: 'Effect',
            when: { effect: 'slide-in' },
        },
        sparkleColor: {
            type: 'color',
            default: '#9E7AFF',
            label: 'Sparkle color',
            description: 'First of the two colors "sparkles-text" alternates between.',
            group: 'Effect',
            when: { effect: 'sparkles-text' },
        },
        sparkleColor2: {
            type: 'color',
            default: '#FE8BBB',
            label: 'Sparkle color 2',
            description: 'Second of the two colors "sparkles-text" alternates between. Set it equal to Sparkle color for a single solid color.',
            group: 'Effect',
            when: { effect: 'sparkles-text' },
        },
        gradientColor: {
            type: 'color',
            default: '#7dd3fc',
            label: 'Gradient color',
            description: 'First accent color "gradient-flow-text" blends into the base text color as it sweeps.',
            group: 'Effect',
            when: { effect: 'gradient-flow-text' },
        },
        gradientColor2: {
            type: 'color',
            default: '#f0abfc',
            label: 'Gradient color 2',
            description: 'Second accent color "gradient-flow-text" blends into the base text color as it sweeps.',
            group: 'Effect',
            when: { effect: 'gradient-flow-text' },
        },
        highlightColor: {
            type: 'color',
            default: '#facc15',
            label: 'Highlight color',
            description: 'Color of the marker stroke "text-highlighter" draws behind the text.',
            group: 'Effect',
            when: { effect: 'text-highlighter' },
        },
        hoverScatter: {
            type: 'boolean',
            default: false,
            label: 'Hover scatter',
            description: 'Units jump to random offsets on hover and settle back with an elastic ease.',
            group: 'Hover',
        },
        hoverIntensity: { type: 'number', default: 24, min: 1, max: 200, unit: 'px', label: 'Scatter intensity', group: 'Hover', when: { hoverScatter: true } },
        hoverDuration: { type: 'number', default: 350, min: 50, max: 3000, unit: 'ms', label: 'Scatter duration', group: 'Hover', when: { hoverScatter: true } },
        hoverReplay: {
            type: 'boolean',
            default: false,
            label: 'Replay on hover',
            description: 'Effects with a built-in hover gesture (letter roll, letter swap, stagger flip 3d) only replay it when this is on. Off by default so hover is never a hidden requirement to see the effect.',
            group: 'Hover',
        },
    },
};
