import { ENTRANCE_FAMILIES, EMPHASIS_FAMILIES, DIRECTIONS } from './catalog.js';

/**
 * Options of the Animate Children module.
 *
 * Attributes: `data-aurora-children="<animation>"` plus
 * `data-aurora-children-<option in kebab-case>`, e.g. `data-aurora-children-stagger`.
 */
export var schema = {
    primary: 'animation',
    options: {
        animation: {
            type: 'enum',
            default: 'fade',
            values: ['none'].concat(ENTRANCE_FAMILIES, EMPHASIS_FAMILIES),
            label: 'Animation',
            description: 'Entrance or emphasis animation. "none" keeps only the hover effect.',
            group: 'Entrance',
        },
        direction: {
            type: 'enum',
            default: 'up',
            values: DIRECTIONS,
            label: 'Direction of travel',
            description: '"up" starts below the final position and moves up.',
            group: 'Entrance',
        },
        alternate: {
            type: 'enum',
            default: 'none',
            values: ['none', 'horizontal', 'vertical'],
            label: 'Alternate direction',
            description: 'Alternates the direction between even and odd children.',
            group: 'Entrance',
        },
        distance: {
            type: 'number',
            default: 32,
            min: 0,
            max: 400,
            unit: 'px',
            label: 'Travel distance',
            group: 'Entrance',
        },
        duration: {
            type: 'number',
            default: 600,
            min: 50,
            max: 5000,
            unit: 'ms',
            label: 'Duration',
            group: 'Timing',
        },
        delay: {
            type: 'number',
            default: 0,
            min: 0,
            max: 10000,
            unit: 'ms',
            label: 'Initial delay',
            group: 'Timing',
        },
        stagger: {
            type: 'number',
            default: 150,
            min: 0,
            max: 2000,
            unit: 'ms',
            label: 'Stagger between children',
            group: 'Timing',
        },
        easing: {
            type: 'string',
            default: 'cubic-bezier(0.22, 1, 0.36, 1)',
            label: 'Easing',
            description: 'Any CSS easing function.',
            group: 'Timing',
        },
        trigger: {
            type: 'enum',
            default: 'scroll',
            values: ['scroll', 'load'],
            label: 'Trigger',
            group: 'Trigger',
        },
        threshold: {
            type: 'number',
            default: 0.15,
            min: 0,
            max: 1,
            step: 0.05,
            label: 'Visible ratio',
            description: 'How much of the element must be visible before the animation starts.',
            group: 'Trigger',
        },
        replay: {
            type: 'boolean',
            default: false,
            label: 'Replay on every scroll',
            group: 'Trigger',
        },
        selector: {
            type: 'selector',
            default: '',
            label: 'Target selector',
            description: 'CSS selector for the elements to animate. Empty animates the direct children.',
            group: 'Targets',
        },
        depth: {
            type: 'number',
            default: 1,
            min: 1,
            max: 10,
            label: 'Depth',
            description: 'Without a selector: how many levels of descendants to animate.',
            group: 'Targets',
        },

        hover: {
            type: 'boolean',
            default: false,
            label: 'Hover effect',
            group: 'Hover',
        },
        hoverPreset: {
            type: 'enum',
            default: 'lift',
            values: ['lift', 'slide', 'scale', 'tilt', 'flip-x', 'flip-y', 'custom'],
            label: 'Hover preset',
            group: 'Hover',
        },
        hoverX: { type: 'number', default: 0, min: -200, max: 200, unit: 'px', label: 'Custom: move X', group: 'Hover' },
        hoverY: { type: 'number', default: -10, min: -200, max: 200, unit: 'px', label: 'Custom: move Y', group: 'Hover' },
        hoverScale: { type: 'number', default: 1.05, min: 0.5, max: 3, step: 0.01, label: 'Custom: scale', group: 'Hover' },
        hoverRotate: { type: 'number', default: 0, min: -180, max: 180, unit: 'deg', label: 'Custom: rotate', group: 'Hover' },
        hoverSkew: { type: 'number', default: 0, min: -60, max: 60, unit: 'deg', label: 'Custom: skew', group: 'Hover' },
        hoverDuration: {
            type: 'number',
            default: 300,
            min: 0,
            max: 2000,
            unit: 'ms',
            label: 'Hover duration',
            group: 'Hover',
        },
        proximity: {
            type: 'boolean',
            default: false,
            label: 'Proximity wave',
            description: 'Neighbours of the hovered child follow the hover effect with a falloff.',
            group: 'Hover',
        },
        proximityIntensity: {
            type: 'number',
            default: 0.5,
            min: 0,
            max: 1,
            step: 0.05,
            label: 'Proximity intensity',
            group: 'Hover',
        },
    },
};
